// SPDX-License-Identifier: CC0-1.0

package main

import (
	"os"
	"strings"
	"testing"
)

// missingFixture is a path that never exists, reused across the
// missing-input tests below.
const missingFixture = "testdata/does-not-exist.json"

// TestRenderGolden exercises the full render() pipeline through the same
// loadRenderInputs() entry point the CLI uses, against fixtures generated by
// running the actual tool (see testdata/golden-body.md). It pins: per-package
// and per-linter table content, the summary row wording, the fail-count
// summary suffix, short-commit truncation in the header and trend key, and
// prior trend rows carried forward alongside a freshly merged one.
func TestRenderGolden(t *testing.T) {
	t.Parallel()

	inputs, err := loadRenderInputs(renderInputPaths{
		coverage: "testdata/coverage.out",
		tests:    "testdata/test-report.jsonl",
		lintDebt: "testdata/lint-debt.json",
		security: "testdata/security.json",
		meta:     "testdata/meta.json",
		prevBody: "testdata/prev-body.md",
	})
	if err != nil {
		t.Fatalf("loadRenderInputs() error = %v", err)
	}

	got := render(inputs)

	want, err := os.ReadFile("testdata/golden-body.md")
	if err != nil {
		t.Fatalf("reading golden file: %v", err)
	}

	if got != string(want) {
		t.Errorf("render() mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestRenderOnlyMeta covers the plan's Phase 1 verification: with nothing but
// --meta provided (first run, every producer artifact missing), every other
// section renders "n/a" instead of failing.
func TestRenderOnlyMeta(t *testing.T) {
	t.Parallel()

	inputs, err := loadRenderInputs(renderInputPaths{
		coverage: "",
		tests:    "",
		lintDebt: "",
		security: "",
		meta:     "testdata/meta.json",
		prevBody: "",
	})
	if err != nil {
		t.Fatalf("loadRenderInputs() error = %v", err)
	}

	body := render(inputs)

	for _, want := range []string{
		"| Go coverage (total) | n/a |",
		"| Lint debt           | n/a |",
		"| Go tests            | n/a |",
		"| Security scan       | n/a |",
		"## Coverage by package\nn/a\n",
		"## Lint debt by linter\nn/a\n",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("render() missing %q in:\n%s", want, body)
		}
	}
}

// TestRenderMissingFilesAreAbsentNotFatal covers the documented CLI contract:
// a path that does not exist on disk (a producer job that never ran) renders
// as absent, the same as an empty flag — it must not error.
func TestRenderMissingFilesAreAbsentNotFatal(t *testing.T) {
	t.Parallel()

	inputs, err := loadRenderInputs(renderInputPaths{
		coverage: missingFixture,
		tests:    missingFixture,
		lintDebt: missingFixture,
		security: missingFixture,
		meta:     missingFixture,
		prevBody: missingFixture,
	})
	if err != nil {
		t.Fatalf("loadRenderInputs() error = %v, want nil (missing files are absent, not fatal)", err)
	}

	if inputs.Coverage != nil || inputs.Tests != nil || inputs.LintDebt != nil || inputs.Security != nil {
		t.Errorf("Inputs = %+v, want every pointer field nil", inputs)
	}

	if inputs.Meta != (Meta{Commit: "", RunURL: "", Updated: ""}) {
		t.Errorf("Meta = %+v, want zero value", inputs.Meta)
	}
}

// TestRenderEmptyMetaCommitTreatedAsAbsent covers a caller that writes the
// literal placeholder "n/a" for an unknown commit: it must be normalised to
// absent, the same as an empty string, or a stale trend row survives forever
// under a non-hex key.
func TestRenderEmptyMetaCommitTreatedAsAbsent(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	metaPath := dir + "/meta.json"

	err := os.WriteFile(metaPath, []byte(`{"commit":"n/a","run_url":"","updated":"2026-08-21 14:32 UTC"}`), 0o600)
	if err != nil {
		t.Fatalf("writing fixture: %v", err)
	}

	inputs, err := loadRenderInputs(renderInputPaths{
		coverage: "",
		tests:    "",
		lintDebt: "",
		security: "",
		meta:     metaPath,
		prevBody: "",
	})
	if err != nil {
		t.Fatalf("loadRenderInputs() error = %v", err)
	}

	if inputs.Meta.Commit != "" {
		t.Errorf("Meta.Commit = %q, want \"\" (n/a normalised away)", inputs.Meta.Commit)
	}
}

func TestShortCommit(t *testing.T) {
	t.Parallel()

	tests := []struct {
		commit string
		want   string
	}{
		{testCommitNew + "deadbeef", testCommitNew},
		{testCommitNew, testCommitNew},
		{"abc", "abc"},
		{"", ""},
	}

	for _, tst := range tests {
		t.Run(tst.commit, func(t *testing.T) {
			t.Parallel()

			if got := shortCommit(tst.commit); got != tst.want {
				t.Errorf("shortCommit(%q) = %q, want %q", tst.commit, got, tst.want)
			}
		})
	}
}
