// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Unit.
const (
	Amount Unit = "amount"
	Bag    Unit = "bag"
	Bottle Unit = "bottle"
	Bunch  Unit = "bunch"
	Can    Unit = "can"
	Cup    Unit = "cup"
	G      Unit = "g"
	Jar    Unit = "jar"
	Kg     Unit = "kg"
	L      Unit = "l"
	Ml     Unit = "ml"
	Pack   Unit = "pack"
)

// Valid indicates whether the value is a known member of the Unit enum.
func (e Unit) Valid() bool {
	switch e {
	case Amount:
		return true
	case Bag:
		return true
	case Bottle:
		return true
	case Bunch:
		return true
	case Can:
		return true
	case Cup:
		return true
	case G:
		return true
	case Jar:
		return true
	case Kg:
		return true
	case L:
		return true
	case Ml:
		return true
	case Pack:
		return true
	default:
		return false
	}
}

// AddItemRequest Request body for adding an item to a list.
type AddItemRequest struct {
	// Checked Whether the item is checked off at creation. Used when an offline
	// check folds into a still-queued create; defaults to false.
	Checked *bool `json:"checked,omitempty"`

	// Name What to buy.
	Name string `json:"name"`

	// Note An optional free-text note.
	Note *string `json:"note,omitempty"`

	// Quantity How many to buy. Defaults to 1.
	Quantity *int32 `json:"quantity,omitempty"`

	// Unit The unit an item's quantity is measured in. A curated German/European
	// grocery set. "amount" is the default and is rendered bare (Stück).
	// This enum is the single source of truth mirrored by the domain
	// (lists.Units) and the items.unit CHECK constraint.
	Unit *Unit `json:"unit,omitempty"`
}

// CopyListRequest Optional request body for copying a list. When omitted (or when `name`
// is absent) the server names the copy "«Original name» (copy)".
type CopyListRequest struct {
	// Name The name for the copy.
	Name *string `json:"name,omitempty"`
}

// CreateListRequest Request body for creating a list.
type CreateListRequest struct {
	// Name The name for the new list.
	Name string `json:"name"`
}

// FieldError A single field-level validation error.
type FieldError struct {
	// Detail Human-readable description of the field error.
	Detail string `json:"detail"`

	// Pointer A JSON Pointer (RFC 6901) identifying the offending field within
	// the request body.
	Pointer *string `json:"pointer,omitempty"`
}

// HealthChecks defines model for HealthChecks.
type HealthChecks struct {
	// Database Status of the database dependency ("ok" when reachable, "error"
	// when unreachable or not configured).
	Database string `json:"database"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Checks HealthChecks `json:"checks"`

	// Status Overall service status (e.g. "ok" or "degraded").
	Status string `json:"status"`
}

// Item A single item on a shopping list.
type Item struct {
	// Checked Whether the item has been checked off (in the cart).
	Checked bool `json:"checked"`

	// CheckedAt When the item was last checked off, if it is checked.
	CheckedAt *time.Time `json:"checkedAt,omitempty"`

	// CreatedAt When the item was created.
	CreatedAt time.Time `json:"createdAt"`

	// Id The item's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// ListId The identifier of the list this item belongs to.
	ListId openapi_types.UUID `json:"listId"`

	// Name What to buy.
	Name string `json:"name"`

	// Note An optional free-text note (e.g. brand or size).
	Note *string `json:"note,omitempty"`

	// Quantity How many to buy. Defaults to 1.
	Quantity int32 `json:"quantity"`

	// Unit The unit an item's quantity is measured in. A curated German/European
	// grocery set. "amount" is the default and is rendered bare (Stück).
	// This enum is the single source of truth mirrored by the domain
	// (lists.Units) and the items.unit CHECK constraint.
	Unit Unit `json:"unit"`

	// UpdatedAt When the item was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
}

// List A shopping list with a summary of its item counts.
type List struct {
	// CheckedItemCount The number of checked items on the list.
	CheckedItemCount int32 `json:"checkedItemCount"`

	// CreatedAt When the list was created.
	CreatedAt time.Time `json:"createdAt"`

	// Id The list's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Name The list's name.
	Name string `json:"name"`

	// OpenItemCount The number of unchecked (open) items on the list.
	OpenItemCount int32 `json:"openItemCount"`

	// UpdatedAt When the list was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ListWithItems defines model for ListWithItems.
type ListWithItems struct {
	// CheckedItemCount The number of checked items on the list.
	CheckedItemCount int32 `json:"checkedItemCount"`

	// CreatedAt When the list was created.
	CreatedAt time.Time `json:"createdAt"`

	// Id The list's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Items All items on the list, open and checked.
	Items []Item `json:"items"`

	// Name The list's name.
	Name string `json:"name"`

	// OpenItemCount The number of unchecked (open) items on the list.
	OpenItemCount int32 `json:"openItemCount"`

	// UpdatedAt When the list was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProblemDetail RFC 9457 (Problem Details for HTTP APIs) error object. The standard
// members are optional; additional extension members may be present.
type ProblemDetail struct {
	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]FieldError `json:"errors,omitempty"`

	// Instance A URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title *string `json:"title,omitempty"`

	// Type A URI reference identifying the problem type. Resolves to a
	// human-readable explanation page (e.g. "/problems/not-found").
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RenameListRequest Request body for renaming a list.
type RenameListRequest struct {
	// Name The new name for the list.
	Name string `json:"name"`
}

// Unit The unit an item's quantity is measured in. A curated German/European
// grocery set. "amount" is the default and is rendered bare (Stück).
// This enum is the single source of truth mirrored by the domain
// (lists.Units) and the items.unit CHECK constraint.
type Unit string

// UpdateItemRequest Request body for updating an item. Only the fields present are changed.
type UpdateItemRequest struct {
	// Name A new name for the item.
	Name *string `json:"name,omitempty"`

	// Note A new note for the item (null clears it).
	Note *string `json:"note,omitempty"`

	// Quantity A new quantity for the item.
	Quantity *int32 `json:"quantity,omitempty"`

	// Unit The unit an item's quantity is measured in. A curated German/European
	// grocery set. "amount" is the default and is rendered bare (Stück).
	// This enum is the single source of truth mirrored by the domain
	// (lists.Units) and the items.unit CHECK constraint.
	Unit *Unit `json:"unit,omitempty"`
}

// User An authenticated user.
type User struct {
	// Email The user's email address, if known.
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id The user's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Name The user's display name.
	Name string `json:"name"`
}

// ItemId defines model for ItemId.
type ItemId = openapi_types.UUID

// ListId defines model for ListId.
type ListId = openapi_types.UUID

// Problem RFC 9457 (Problem Details for HTTP APIs) error object. The standard
// members are optional; additional extension members may be present.
type Problem = ProblemDetail

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = CreateListRequest

// RenameListJSONRequestBody defines body for RenameList for application/json ContentType.
type RenameListJSONRequestBody = RenameListRequest

// CopyListJSONRequestBody defines body for CopyList for application/json ContentType.
type CopyListJSONRequestBody = CopyListRequest

// AddItemJSONRequestBody defines body for AddItem for application/json ContentType.
type AddItemJSONRequestBody = AddItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// Getter for additional properties for ProblemDetail. Returns the specified
// element and whether it was found
func (a ProblemDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetail
func (a *ProblemDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a *ProblemDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["errors"]; found {
		err = json.Unmarshal(raw, &a.Errors)
		if err != nil {
			return fmt.Errorf("error reading 'errors': %w", err)
		}
		delete(object, "errors")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a ProblemDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Errors != nil {
		object["errors"], err = json.Marshal(a.Errors)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errors': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List all lists
	// (GET /lists)
	ListLists(w http.ResponseWriter, r *http.Request)
	// Create a list
	// (POST /lists)
	CreateList(w http.ResponseWriter, r *http.Request)
	// Delete a list
	// (DELETE /lists/{listId})
	DeleteList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Get a list with its items
	// (GET /lists/{listId})
	GetList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Rename a list
	// (PATCH /lists/{listId})
	RenameList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Copy a list
	// (POST /lists/{listId}/copy)
	CopyList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Add an item to a list
	// (POST /lists/{listId}/items)
	AddItem(w http.ResponseWriter, r *http.Request, listId ListId)
	// Remove an item
	// (DELETE /lists/{listId}/items/{itemId})
	DeleteItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Update an item
	// (PATCH /lists/{listId}/items/{itemId})
	UpdateItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Check off an item
	// (POST /lists/{listId}/items/{itemId}/check)
	CheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Restore a deleted item
	// (POST /lists/{listId}/items/{itemId}/restore)
	RestoreItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Uncheck an item
	// (POST /lists/{listId}/items/{itemId}/uncheck)
	UncheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Get the authenticated user
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all lists
// (GET /lists)
func (_ Unimplemented) ListLists(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a list
// (POST /lists)
func (_ Unimplemented) CreateList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a list
// (DELETE /lists/{listId})
func (_ Unimplemented) DeleteList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a list with its items
// (GET /lists/{listId})
func (_ Unimplemented) GetList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename a list
// (PATCH /lists/{listId})
func (_ Unimplemented) RenameList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Copy a list
// (POST /lists/{listId}/copy)
func (_ Unimplemented) CopyList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add an item to a list
// (POST /lists/{listId}/items)
func (_ Unimplemented) AddItem(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an item
// (DELETE /lists/{listId}/items/{itemId})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an item
// (PATCH /lists/{listId}/items/{itemId})
func (_ Unimplemented) UpdateItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check off an item
// (POST /lists/{listId}/items/{itemId}/check)
func (_ Unimplemented) CheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore a deleted item
// (POST /lists/{listId}/items/{itemId}/restore)
func (_ Unimplemented) RestoreItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Uncheck an item
// (POST /lists/{listId}/items/{itemId}/uncheck)
func (_ Unimplemented) UncheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the authenticated user
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLists operation middleware
func (siw *ServerInterfaceWrapper) ListLists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateList operation middleware
func (siw *ServerInterfaceWrapper) CreateList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteList operation middleware
func (siw *ServerInterfaceWrapper) DeleteList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameList operation middleware
func (siw *ServerInterfaceWrapper) RenameList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CopyList operation middleware
func (siw *ServerInterfaceWrapper) CopyList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CopyList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItem operation middleware
func (siw *ServerInterfaceWrapper) AddItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItem(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckItem operation middleware
func (siw *ServerInterfaceWrapper) CheckItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreItem operation middleware
func (siw *ServerInterfaceWrapper) RestoreItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UncheckItem operation middleware
func (siw *ServerInterfaceWrapper) UncheckItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UncheckItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lists", wrapper.ListLists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists", wrapper.CreateList)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/lists/{listId}", wrapper.DeleteList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lists/{listId}", wrapper.GetList)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/lists/{listId}", wrapper.RenameList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/copy", wrapper.CopyList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items", wrapper.AddItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/lists/{listId}/items/{itemId}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/lists/{listId}/items/{itemId}", wrapper.UpdateItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items/{itemId}/check", wrapper.CheckItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items/{itemId}/restore", wrapper.RestoreItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items/{itemId}/uncheck", wrapper.UncheckItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fvvctu4EX+VHbYzJ08pyc5d2znnk5vkLm4vl4wTz304ZuYgYiUiJgEGAO2oHj1RH6H9dH2xzgIgRYqU",
	"LNtKMtMvd44JLBa7v/0P30apKkolUVoTnd5GJdOsQIva/evcYnHO6SeOJtWitELJ6DR6lyEIi8U3Biop",
	"PlYIgqO0Yi5QT6I4ErSoZDaL4kiyAqPTSHhScaTxYyU08ujU6grjyKQZFozOmCtdMBudRlUlaKVdlrTT",
	"WC3kIlqt4ugnYew2fnJh7D34yT2px/Czos2mVNKgk9YbrWY5FvRjqqRFaelHVpa5SBlxOi39ij99MMT2",
	"beusP2qcR6fRH6ZrdUz9VzMNdJ+jZSL353avfyYBtVYaVJpWWiOfAElkpvgShAEm4eKHZ/D9d3/+KwRa",
	"4IkZULMPmFq4ETZL5DPP9fjdskTYxvcEXlyjXkLi5JFE7gQg4Y7ZzKi8spjIy4tzGCVRvdFMb01eLVZJ",
	"dAQ2YxY0GpVfowGrgEFWFUyONTLOZjkCfipzJt3JiSzZAsGgvkYOsyXYDOHszfkkkQ4QQUQkwTPOCa4X",
	"+LFCY/sYCR+8VOZKA+NcyAVJh7DpOSFUEGBKrUrUVnjFphmmVxhwN2dVbqPTOcsNbirilwxthtpx6YgK",
	"A2EzqPkcmIVUo7vZBC4NcrjJUBILaj7PhcREuuUwVzk3IKRjyliR5+OPFVbI/X58CoERJ0HHC4mkwehM",
	"qRyZjFY13m97nDJLW2fVku5bCPkTyoXNotOTHtDjSCo7QONMgnI/sxzmGnFs8ZMFWkskZZXnpM7arnpE",
	"P1ZMWmGXHbGebIr0pbqBgsllzSw8b138hA5qzFRI++0TfxlRVEX7KkJaXKCmYysp7F0Wd0lrvH3XzuFX",
	"L8j3DUlvOUTxmSqX5Jm2Qu91LSW9icFUlUsHQo88+IXgoAphLXIYKe3x8Rsd/VsiydJmBqU9cghzVqGB",
	"Phr3C6IGSfT7v15rsRB0IH37/d8woi9HSeQx0gX3MD7If9AXx2VN+06krIak4wC7Uz490/RGspbLQ5mW",
	"eNMQuIvxvVT9g8CcvyBfO2AOYIRc5AhzWjTO8RpzuGa54M7gvYvuX4V7t94j97LrFFsfQc3d7dw5a7I9",
	"AysVwX6Q07+/ff0zvPHfYUTR4S/fH58c1WHTYZKOUPM5Sucm/WEUJ4RMJH1rg7njfLYINVx0SKwvkeU2",
	"e0auz2chXQkxy2bMDCj8rWW2MrU86nXAsUTJUaZLCkLqKom8HWlkaUbSjCGJnNySKJHuUyWbj6A0OTFI",
	"lZyLRaWRH+11vZrL7Rf07PYvmDYX3+WUOkKi2NdQ2/A216hZnjv3IFIEvw5GOFlMIIhDaUgijgvNOPIk",
	"Oprceb1wWlwzO3RLir877MJFRCUpomWqLAlVe8TbnfE1YwZmiLITZUdCepfFtG3frBUUw/IzO3iGXB9w",
	"wwzkzNj2ATGIOQjbCu6dMMSZxbEVBe4TBH0435ORsHjraT3q4gG5+x1Zb1xnzsOEG1K1UdJqsJkw/hoz",
	"zJVcUPDe66y9kpdHpyvBNmaaSU6mYcQ/8ej/I4eJo6rk+yPMQb1QnFS4N842PIXTZFNeOQ22BBWYb0ww",
	"attAm9shB0NZxKCDafsTF6TIyVRFwfSSgChsgF+qKmnNVo9DDuwZLdmSW1TFzCO79gZE1JBPq6E+qMy+",
	"Avcxe3+XQ5r9rhL5gabYIksLBs1RlSj3lmwla9mOaN/Rg0W8D+4bER8M9wHu3SvHfXzdF/W/CJvRbodW",
	"luev59Hpr7sdgDOWVbyZbIiayoYR5Xlf1DHQRYDcYivSNRR2ne5ygXU9wLRmy77IHKX+nd/3OhwhjqiF",
	"TwC8ied527jNhM7rNktIWJwL7/XftOTg/flGGVI3SUabXRKqJ16+e/cGzt6cm6O62eKY9a0WY5nkTPNE",
	"FkhINsA0NuHmKayZAPxkURpK4+ulBVvCDKHUSLXdUI22rUY429E6AVNiKuYipSDjAnDoDsl02EzdrQaQ",
	"8cOOcsbEoYPhm0WzHPcGSKuU6sEkjoQkkaZDYRwuL85B4xzdVXolS3Pt7nXX/k2LcbN7SA7b8mrSswNB",
	"SKhTxetKsyPcOvMJva893ZUVNsctsU3beFPRreDWOguI7qBy/S/uK8sOWbhoN+0SuQN6rmlXFxzrJqBU",
	"djxXlXQVh4P5vloZaixcIDnb+zUWNO15YGMBb7rNhYM2Fi5DRtckkRErQqDos0IZVN23/MZAnVtRQVIg",
	"M1SygpATOIO00hRY4EfUBZPTFxVdlslELrRKUS/BoCUd+cN8M9eV0p4N5/mFIbFxJKozcmujt/a//0mv",
	"SIXvCPooq6LeGEo9oyodLEFXNoNCkKGvW7hcFUzIRI5IiGZCtzdH7rQ6HTUTd8tnL188+weV4sZqJmrv",
	"SCeSOBsZLaI4uqL/FDkln6RWll5FcTRTluwqjlJGGz8wTT9XJX2iVIP+zxYtlaxN5tIF5fv1lF0gb3WV",
	"J/Ba5st1t8bUXt7FhzRjcoF8/67cWR+F7pQHd3A9PSqB2vRgRIUPpDkyTbH1IbVQ/5gGppusf84Gbt/Q",
	"zGBHTAKrbEbeL3UGUxkc6NVhMRiGnU0a1N8YcCso3Gs0xjUKrqS6kZ1reip7SHRbHh/OOnQeH8hyYcqc",
	"Lbfl81uz3r5bW7lAPlcDjbsyF/aKVfN6mEMVY4rSN/nCiO7d6+evW6GxuymKo2vUxpM7npxMjutSg5Ui",
	"Oo2+nRxPvnV+wGZOd9PM9c/oxwUO2nKptDWgNtpnflvjm0zTcuTqhrwSsiKRTcdRoJnAWX7DluQ1baWl",
	"8UnDk+PjpyAkZSfWx1a2zBXjzho8US8HwpuLouc8Oo1+ROv7ftHGsPHJ8fGOQeP9Boyd7uTAfNF/b129",
	"nj4Iyq3c8hC1hs9pGK9HmX5251MYUmxH1AQ5tjCu6bg0VEa8p+VTFyp2qM8LG91wstMQiAFZmm1pC2wW",
	"OIlsNwqAyiJ3sHPY18IIynWsCuf4FB5GUkGJekwWBOpGojaZKI+GFEr5yk/uJo9U6F5JdqgBN6uw/gS5",
	"vuYh1EmHuuIsD/es1en//d6NJobCqR8VGWAuXgw0dQh3C3GNsnFOXeGuZ01hsI/G/k3x5cEspT/MWnUd",
	"InnyVU+zJwdjwCu0r0Dy36GjEBLTx+vRXzakygNqbIxyeuvbfSuv0hyHco3n7vcmkHMm1y/gNxXqNzUK",
	"7Qj1u+3dKNfT8YzwQ0jCs7FdEvFun8TqtHivJsZACBgWwPFBUbXuMG2BV6O2bsPlkaL9EW0NCSePhviw",
	"32g9T9rS/lovmYbnQqv3Lg1IsyEN+ek5k4CfhLHtmVRXC+tq8zO5ln45u5drOf4irsXVzQd0Lf6y93Et",
	"01SVy80XaveDwB4xx+GQpMmEJCz4KC+VHAdvEoaYIQXyVS5tSuRoM5MAlosrPArZB5V9bmjVNLgn8DMr",
	"MG7qotjV9XEiiYarySjlcPWivkYeAzNNle0ObuXqSnPUvhUZsJnI+vlX3YU89a06qXwBKQyYisCCfP14",
	"RPg2Pk/krmckMVgtCsKDVTAXPp99cnw8TjOmWWrDoxTIRSHsUBJUv5j5XFF640HOqv9W70vHZP985gAx",
	"mbR0H7Np0sQD280Z52bg7Rw0b3Bc28j7rqfr2r/9bO3kqX9I4rDeAuoQYsLrvs8EmI23g184p/Ojkt34",
	"8b2Sx+PnjPO+1u6BpOmtf8i7M9W7wEJd4xoec62KVsd1KMVrlLtPiteMq7U7iB8mIhGpmuUDJh/xnSvD",
	"K+sdaYpvRZpWz1duhA7/Zgm39xs3X221+o8wypmx4xstLI5vhDThaaL0Ew0LyIU1g9Xsukf6mSyz34T9",
	"wlnRLuMMY9uDGae/7A4M3mmVU5dbPNzd3w+sg4HhFdNXa9Nn6wfQ3WdZcM6xKBUp6NQvCW1zlmtkfJnI",
	"9hsL/8hcqrEq6wfkvrRyBANMjWUWB9MNojTsYb4MUNpXOUgW4B6Juxflj8CKRmOVxq+KlgvPg6uR1dx2",
	"02w3uA6Dtg5ePOetOQv5NuZe5ElloSHyGNAEzr4mbIKCDoebcCdg0Jbzg8ATypivDJ66v9LxFQE2rh7r",
	"Yycw7sGTyOBu/OrHu5pLT/1roqaSh3Y34VJ3OBs/VtrZCLNhygRCfsDU4U8GbYXkYQLnEl6dhBejBpgf",
	"pdgME5kxzVPFkQPHa09ndPl2fDY5OXoa3uNqLHOW+jmzRpa3p3pCSRASXj3ZMmd5hZ9TY27uuEVjQ6PH",
	"w3TW7CD1lgL98NAuSYe02/1JibfjSufRaTRlpZhenzgrDJt6w7z+pKwRLssBJXd/ieBam2G0FwY75AT2",
	"E8f67whrhvt737YHBqae2Am9bqy2/vbPRKv3q/8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
