// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Unit.
const (
	Amount Unit = "amount"
	Bag    Unit = "bag"
	Bottle Unit = "bottle"
	Bunch  Unit = "bunch"
	Can    Unit = "can"
	Cup    Unit = "cup"
	G      Unit = "g"
	Jar    Unit = "jar"
	Kg     Unit = "kg"
	L      Unit = "l"
	Ml     Unit = "ml"
	Pack   Unit = "pack"
)

// Valid indicates whether the value is a known member of the Unit enum.
func (e Unit) Valid() bool {
	switch e {
	case Amount:
		return true
	case Bag:
		return true
	case Bottle:
		return true
	case Bunch:
		return true
	case Can:
		return true
	case Cup:
		return true
	case G:
		return true
	case Jar:
		return true
	case Kg:
		return true
	case L:
		return true
	case Ml:
		return true
	case Pack:
		return true
	default:
		return false
	}
}

// AddItemRequest Request body for adding an item to a list.
type AddItemRequest struct {
	// Checked Whether the item is checked off at creation. Used when an offline
	// check folds into a still-queued create; defaults to false.
	Checked *bool `json:"checked,omitempty"`

	// Name What to buy.
	Name string `json:"name"`

	// Note An optional free-text note.
	Note *string `json:"note,omitempty"`

	// Quantity How many to buy. Defaults to 1.
	Quantity *int32 `json:"quantity,omitempty"`

	// Unit The unit an item's quantity is measured in. A curated German/European
	// grocery set. "amount" is the default and is rendered bare (Stück).
	// This enum is the single source of truth mirrored by the domain
	// (lists.Units) and the items.unit CHECK constraint.
	Unit *Unit `json:"unit,omitempty"`
}

// Attribution The user credited with an action — creating a list, adding an item, or
// buying one. Only the id is stored; the name is resolved when the
// resource is read, so a profile rename applies retroactively.
//
// Clients render "you" by comparing `id` against the id from `GET /me`
// rather than by matching the name.
type Attribution struct {
	// Id The acting user's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Name The acting user's display name, or null when no member record
	// matches the id (the account has never signed in since attribution
	// was introduced). Clients should show nothing rather than a bare id.
	Name *string `json:"name,omitempty"`
}

// CopyListRequest Optional request body for copying a list. When omitted (or when `name`
// is absent) the server names the copy "«Original name» (copy)".
type CopyListRequest struct {
	// Name The name for the copy.
	Name *string `json:"name,omitempty"`
}

// CreateListRequest Request body for creating a list.
type CreateListRequest struct {
	// Name The name for the new list.
	Name string `json:"name"`
}

// FieldError A single field-level validation error.
type FieldError struct {
	// Detail Human-readable description of the field error.
	Detail string `json:"detail"`

	// Pointer A JSON Pointer (RFC 6901) identifying the offending field within
	// the request body.
	Pointer *string `json:"pointer,omitempty"`
}

// HealthChecks defines model for HealthChecks.
type HealthChecks struct {
	// Database Status of the database dependency ("ok" when reachable, "error"
	// when unreachable or not configured).
	Database string `json:"database"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Checks HealthChecks `json:"checks"`

	// Status Overall service status (e.g. "ok" or "degraded").
	Status string `json:"status"`
}

// Item A single item on a shopping list.
type Item struct {
	// AddedBy Who added the item to the list. Absent when unknown — items added
	// before attribution was introduced carry no adder.
	AddedBy *Attribution `json:"addedBy,omitempty"`

	// BoughtBy Who checked the item off, i.e. bought it. Absent while the item is
	// open: unchecking clears it, so it never names a buyer for something
	// still to be bought. Re-checking credits whoever checked it that
	// time, who need not be the adder.
	BoughtBy *Attribution `json:"boughtBy,omitempty"`

	// Checked Whether the item has been checked off (in the cart).
	Checked bool `json:"checked"`

	// CheckedAt When the item was last checked off, if it is checked.
	CheckedAt *time.Time `json:"checkedAt,omitempty"`

	// CreatedAt When the item was created.
	CreatedAt time.Time `json:"createdAt"`

	// Id The item's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// ListId The identifier of the list this item belongs to.
	ListId openapi_types.UUID `json:"listId"`

	// Name What to buy.
	Name string `json:"name"`

	// Note An optional free-text note (e.g. brand or size).
	Note *string `json:"note,omitempty"`

	// Quantity How many to buy. Defaults to 1.
	Quantity int32 `json:"quantity"`

	// Unit The unit an item's quantity is measured in. A curated German/European
	// grocery set. "amount" is the default and is rendered bare (Stück).
	// This enum is the single source of truth mirrored by the domain
	// (lists.Units) and the items.unit CHECK constraint.
	Unit Unit `json:"unit"`

	// UpdatedAt When the item was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
}

// List A shopping list with a summary of its item counts.
type List struct {
	// CheckedItemCount The number of checked items on the list.
	CheckedItemCount int32 `json:"checkedItemCount"`

	// CreatedAt When the list was created.
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy Who created the list. Absent when unknown — lists created before
	// attribution was introduced carry no creator.
	CreatedBy *Attribution `json:"createdBy,omitempty"`

	// Id The list's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Name The list's name.
	Name string `json:"name"`

	// OpenItemCount The number of unchecked (open) items on the list.
	OpenItemCount int32 `json:"openItemCount"`

	// UpdatedAt When the list was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ListWithItems defines model for ListWithItems.
type ListWithItems struct {
	// CheckedItemCount The number of checked items on the list.
	CheckedItemCount int32 `json:"checkedItemCount"`

	// CreatedAt When the list was created.
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy Who created the list. Absent when unknown — lists created before
	// attribution was introduced carry no creator.
	CreatedBy *Attribution `json:"createdBy,omitempty"`

	// Id The list's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Items All items on the list, open and checked.
	Items []Item `json:"items"`

	// Name The list's name.
	Name string `json:"name"`

	// OpenItemCount The number of unchecked (open) items on the list.
	OpenItemCount int32 `json:"openItemCount"`

	// UpdatedAt When the list was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProblemDetail RFC 9457 (Problem Details for HTTP APIs) error object. The standard
// members are optional; additional extension members may be present.
type ProblemDetail struct {
	// Detail A human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors, when applicable.
	Errors *[]FieldError `json:"errors,omitempty"`

	// Instance A URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title *string `json:"title,omitempty"`

	// Type A URI reference identifying the problem type. Resolves to a
	// human-readable explanation page (e.g. "/problems/not-found").
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RenameListRequest Request body for renaming a list.
type RenameListRequest struct {
	// Name The new name for the list.
	Name string `json:"name"`
}

// Unit The unit an item's quantity is measured in. A curated German/European
// grocery set. "amount" is the default and is rendered bare (Stück).
// This enum is the single source of truth mirrored by the domain
// (lists.Units) and the items.unit CHECK constraint.
type Unit string

// UpdateItemRequest Request body for updating an item. Only the fields present are changed.
type UpdateItemRequest struct {
	// Name A new name for the item.
	Name *string `json:"name,omitempty"`

	// Note A new note for the item (null clears it).
	Note *string `json:"note,omitempty"`

	// Quantity A new quantity for the item.
	Quantity *int32 `json:"quantity,omitempty"`

	// Unit The unit an item's quantity is measured in. A curated German/European
	// grocery set. "amount" is the default and is rendered bare (Stück).
	// This enum is the single source of truth mirrored by the domain
	// (lists.Units) and the items.unit CHECK constraint.
	Unit *Unit `json:"unit,omitempty"`
}

// User An authenticated user.
type User struct {
	// Email The user's email address, if known.
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id The user's unique identifier.
	Id openapi_types.UUID `json:"id"`

	// Name The user's display name.
	Name string `json:"name"`
}

// ItemId defines model for ItemId.
type ItemId = openapi_types.UUID

// ListId defines model for ListId.
type ListId = openapi_types.UUID

// Problem RFC 9457 (Problem Details for HTTP APIs) error object. The standard
// members are optional; additional extension members may be present.
type Problem = ProblemDetail

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = CreateListRequest

// RenameListJSONRequestBody defines body for RenameList for application/json ContentType.
type RenameListJSONRequestBody = RenameListRequest

// CopyListJSONRequestBody defines body for CopyList for application/json ContentType.
type CopyListJSONRequestBody = CopyListRequest

// AddItemJSONRequestBody defines body for AddItem for application/json ContentType.
type AddItemJSONRequestBody = AddItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// Getter for additional properties for ProblemDetail. Returns the specified
// element and whether it was found
func (a ProblemDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetail
func (a *ProblemDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a *ProblemDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["errors"]; found {
		err = json.Unmarshal(raw, &a.Errors)
		if err != nil {
			return fmt.Errorf("error reading 'errors': %w", err)
		}
		delete(object, "errors")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetail to handle AdditionalProperties
func (a ProblemDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Errors != nil {
		object["errors"], err = json.Marshal(a.Errors)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'errors': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List all lists
	// (GET /lists)
	ListLists(w http.ResponseWriter, r *http.Request)
	// Create a list
	// (POST /lists)
	CreateList(w http.ResponseWriter, r *http.Request)
	// Delete a list
	// (DELETE /lists/{listId})
	DeleteList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Get a list with its items
	// (GET /lists/{listId})
	GetList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Rename a list
	// (PATCH /lists/{listId})
	RenameList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Copy a list
	// (POST /lists/{listId}/copy)
	CopyList(w http.ResponseWriter, r *http.Request, listId ListId)
	// Add an item to a list
	// (POST /lists/{listId}/items)
	AddItem(w http.ResponseWriter, r *http.Request, listId ListId)
	// Remove an item
	// (DELETE /lists/{listId}/items/{itemId})
	DeleteItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Update an item
	// (PATCH /lists/{listId}/items/{itemId})
	UpdateItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Check off an item
	// (POST /lists/{listId}/items/{itemId}/check)
	CheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Restore a deleted item
	// (POST /lists/{listId}/items/{itemId}/restore)
	RestoreItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Uncheck an item
	// (POST /lists/{listId}/items/{itemId}/uncheck)
	UncheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId)
	// Get the authenticated user
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all lists
// (GET /lists)
func (_ Unimplemented) ListLists(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a list
// (POST /lists)
func (_ Unimplemented) CreateList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a list
// (DELETE /lists/{listId})
func (_ Unimplemented) DeleteList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a list with its items
// (GET /lists/{listId})
func (_ Unimplemented) GetList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename a list
// (PATCH /lists/{listId})
func (_ Unimplemented) RenameList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Copy a list
// (POST /lists/{listId}/copy)
func (_ Unimplemented) CopyList(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add an item to a list
// (POST /lists/{listId}/items)
func (_ Unimplemented) AddItem(w http.ResponseWriter, r *http.Request, listId ListId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an item
// (DELETE /lists/{listId}/items/{itemId})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an item
// (PATCH /lists/{listId}/items/{itemId})
func (_ Unimplemented) UpdateItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check off an item
// (POST /lists/{listId}/items/{itemId}/check)
func (_ Unimplemented) CheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore a deleted item
// (POST /lists/{listId}/items/{itemId}/restore)
func (_ Unimplemented) RestoreItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Uncheck an item
// (POST /lists/{listId}/items/{itemId}/uncheck)
func (_ Unimplemented) UncheckItem(w http.ResponseWriter, r *http.Request, listId ListId, itemId ItemId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the authenticated user
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLists operation middleware
func (siw *ServerInterfaceWrapper) ListLists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateList operation middleware
func (siw *ServerInterfaceWrapper) CreateList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteList operation middleware
func (siw *ServerInterfaceWrapper) DeleteList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameList operation middleware
func (siw *ServerInterfaceWrapper) RenameList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CopyList operation middleware
func (siw *ServerInterfaceWrapper) CopyList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CopyList(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItem operation middleware
func (siw *ServerInterfaceWrapper) AddItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItem(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckItem operation middleware
func (siw *ServerInterfaceWrapper) CheckItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreItem operation middleware
func (siw *ServerInterfaceWrapper) RestoreItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UncheckItem operation middleware
func (siw *ServerInterfaceWrapper) UncheckItem(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "listId" -------------
	var listId ListId

	err = runtime.BindStyledParameterWithOptions("simple", "listId", chi.URLParam(r, "listId"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "listId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId ItemId

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UncheckItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lists", wrapper.ListLists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists", wrapper.CreateList)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/lists/{listId}", wrapper.DeleteList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/lists/{listId}", wrapper.GetList)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/lists/{listId}", wrapper.RenameList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/copy", wrapper.CopyList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items", wrapper.AddItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/lists/{listId}/items/{itemId}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/lists/{listId}/items/{itemId}", wrapper.UpdateItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items/{itemId}/check", wrapper.CheckItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items/{itemId}/restore", wrapper.RestoreItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/lists/{listId}/items/{itemId}/uncheck", wrapper.UncheckItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3DvtbtvIdq9ywBZYG5VkO3vb4jq/fLPZjdvdm8BJsD8uA2TEORJnTc4wM0N71cBAH6Jv0Udof23fpE9S",
	"nDNDihQpWbaVBOifXcXknDnf3/ycZKasjEbtXXL+OamEFSV6tPyvS4/lpaRfEl1mVeWV0cl58i5HUB7L",
	"7xzUWn2qEZRE7dVCoZ0lk0TRS5XweTJJtCgxOU9UADVJLH6qlUWZnHtb4yRxWY6loDsWxpbCJ+dJXSt6",
	"068qOum8VXqZ3N1Nkp+V89vwKZTzD8CnCKCegs8dHXaV0Q6ZW2+smRdY0s/MaI/a009RVYXKBGF6UoU3",
	"/uE3R2h/7tz19xYXyXnydydrcZyEp+4kwv0BvVBFuLdP/oUGtNZYMFlWW4tyBsSRuZErUA6EhqsfX8Cf",
	"//SP/wwRFgRgDsz8N8w83Cqfp/pFwHr6blUhbMN7Bi9v0K4gZX6kCd8AxNypmDtT1B5T/f7qEo7SpDno",
	"Tj67ol7epckx+Fx4sOhMcYMOvAEBeV0KPbUopJgXCPh7VQjNN6e6EksEh/YGJcxX4HOEizeXs1SzQkQW",
	"EQcvpCR1vcJPNTo/1JH4IHBlYSwIKZVeEndINwMmpBWkMJU1FVqvgmCzHLNrjHq3EHXhk/OFKBxuCuLX",
	"HH2OlrFkoMpBPAxmsQDhIbPIlM3gvUMJtzlqQsEsFoXSmGp+HRamkA6UZqScV0Ux/VRjjTKcx+cQEWEO",
	"Mi7EklZH58YUKHRy1+j75wGmwtPReb0iekulf0a99HlyfjZQ9EmijR+BcaHB8G9RwMIiTj3+7oHeJZC6",
	"LgoSZ2NXA6CfaqG98qseW882WfrK3EIp9KpBFn7oEH5GF7VmqrT//lkgRpV12SVFaY9LtHRtrZW/z+Le",
	"0zvBvhvn8LfAyA8tyGA5BPHCe6vmdUB4zDXVDi0JTipPIlc+J5GLjF6B//33/4hKQcrIGjjZ0M0JGJvq",
	"eb2ivxmNM3iti2ALSpKOOW8syuf8F0KT/hZNLKqYzzHV9KfaZvGxkBNwpF+VNQtVIFjks2z4SG94awjJ",
	"GyxWs1Sn+kWhiE30okQLabIydZqQWRIPBQkWPir5EcRSKO18g+HCmhI+/vTyHZyU+DHVVkQrEZoOl8Jn",
	"OZ1t0A+q3LdBtcXtE4J6ySze5v3v8ePbTGQIXSpXFWLFOJJMgHQ88FcbKLGcowWLmbEy1UwVebjAgyPP",
	"4DJTaw+5cKDxBi04tdQoQWlwSmcIYq1Lqb4V7AOskXWG8ngGjQBcbupC0v9uyd6YeV2mCpgLS9cGTt5j",
	"iht6ruSolr8w1Yri71YH+7rxBXbT02amWq21ewa/EsdMqTyZw5GxgYUfia0fU03xZO5Q+2PmHft+yzwP",
	"zCRokCZ//Odrq5aKLqRnf/wXHNGT4zQZU5/tImadJywb2Pf6w7sx7rBb3smfQQDasPrZY5HWeNsCuA/x",
	"vRzajwoL+ZIyihGnT4q6LBAW9NK0wBss4EYUSnJYC4nIkBQZkpcBuFf90N95CGbB1PE9a7AD460MOfdR",
	"TP/l7eu/wpvwHI4oB/qnP5+eHTfuYdX4HLNYoGaHGy4jD610qulZV5l7IXYLUyOhY2x9haLw+QsK8CHX",
	"7nNIeDEXbkTgb73wtWv40bwHEivywzpbUaplrtMk2JFFkeXEzQmkCfMtTVLNj2rdPmT3ZTxkRi/Usrbk",
	"X/Yhr8FyO4EB3SGBWUv4rtDbYxJleC20DW9zg1YUBbsHlSGE9+AIZ8sZRHYYilESl1ZIlGlyPLuXvHjb",
	"pEF2jErKMnfYBed9hnywy01VkVaNW7eQEuVfOP0RRfF6kZz/bTdrunnG3Ydh7mmAQa6zT2/4d3C6F+xT",
	"IerBtTa3IfegN104meo5LoztRSHoByHIhLUrCnd0wnIePknmpl7m/rC0NHlzS41ZLCagZjiDcB2oLlWU",
	"wHTS7lSbCvU51CGhJilkBQrrQHlOe5SPETgEFkHJJVr2qc6UyDE11Zx6c+qJ8dYZXOF0DZOTOge3uWFg",
	"DdLKc52Taq8oVbjNDWhEyRY3D4h2+dcrMHYWFJQ5zBF1r6w4UjpEL2F9V8k7VUB8/cKP3qHXF5C4C+F8",
	"94IJqAWRtK5memmVFB6nROg+WX+oX/ZEJL689bYBdPWIZsW96WGxo+uwBtX4Z3obfK5cIGOOhdFLqlae",
	"kIpuVGtPrs+im5xboSV5Saf+DY//fxRtk6Su5P4axqpeGkki3FvPhgnzZN1PYgl2GBWRXxt51wa62I7F",
	"GkooR2NNN7TEihJcXZbCrkgRyScxjVxvuK0tDYplL+iVLWlmzSWNWXQcG0ULo9eBZUyYQwHuY/aBlseY",
	"fTxw4AAUgO4RQulpizWEGJrqfYIonzFNGFCPaG0+obiNYLniHjtJEXRvBYmBlgu6CvXxozVlH/NtNeVg",
	"5huttk/yZGgmDzXeX5XP6bTbXzPZ5u8mm+mzaqBs+IKiGLJ6AkQIkHfvBOwWwq7bObtdV7jCWrEasowh",
	"DWke2NFFDIdmGfKY4KmKouuj3Izu6ze5Q3qsQvB60+FDCEsbhXXT3D7a7G5TNvfq3bs3cPHm0h03TXJG",
	"NrTInRdaCm7XcPfGgbDYRs3nsEYC8HeP2pExN6+WYkXJXGWR3MJY12Fb1Xuxo+UNrsJMLVQW0nflmq6+",
	"zsbNlKka0YwfdxTobhI7z6HJPy9wbwXpNAcGajJJlCaWZmPZCLy/ugSLC2RSBkV4S3af3LV/s2ranh7j",
	"w7ZKkeTMShBLxMzIpnfSY26TwMWZxZ7uyitf4JYQbf1kU9CdGN25CwjuqHDDHx7Kyx5YuOoOW1K9Q/V4",
	"2NKU0OvhjTZ+ujC15hqa1XxfqYy1yq64zfywVhm3ph/ZKsPbfrvsoK2y9zExbXPhRJQxUIzMAbTyTU//",
	"OwdNikh1VYnC1ZY7wTO4gKy2nEv8hLYU+uRlTcQKneqlNRnaFTj0JKNwWRjCcXMooMGeXzWNespJyK0d",
	"vfX/89/ZNYnwHak+6rpsDsbmRZwPkHba2udQKjL09ehNmlIoneojTnlmRL075tuarNrNmMoXr16++FfI",
	"jHbeCtV4R7qR2NnyaJlMkmv6T1lQDk1iFdl1MknmxpNdTZJM0MHfhKXfdUWPKNWg/4tlRyRrk3nPQflh",
	"s0AO5J2JS2fCwi1B13h5jg9ZLvQS5f595ouhFvItj568BXhUyXXhwREPJNpGx2NKuuE1rZpuov4lB29D",
	"Q3OjPV4NovY5eb+MDaZ2ONJ9xnI0DDezue8c8BsU7i06x/0OTu97ZAYoe3B0Wx7/hYZUI9Op2QOy3qFb",
	"u+NAvjAjreiqUP5a1ItmCE+Fb4Y6tK3jasW71z+87oTG/qFkktygdQHc6exsdtqUGqJSyXny/ex09j37",
	"AZ+z7E5y7gjTzyWO2nJlrHdgNhrC4Vjrm1zbRJfmlrwSijLVbQ9doZvBRXErVjz4rK12IWl4dnr6HJSm",
	"7CTMMyuxKoyQoVPIQAMfSN84il7K5Dz5CX3oZCcbSyLPTk93LIg8bDGk128f2QsJzzukN/M0RbkVvx6j",
	"1vg9LeLNCkrYuQgpDAm2x2pSObF03EZfOSojPtDrJxwqdogvMBt5qaTX15gAiizf0t3YLHBS3e13AJVF",
	"oSwnh32jnKJcx5t4T5zVHmkDFdopD+jNrUbrclUdjwmU8pWfmZInCnSvJDvWgJtV2HDzpyHzEOKkS7k4",
	"KyKdjTjDvz/wsG0snIbhpwPB8WKkN0V6t1Q3qFvn1GfuenoaF7LQ+b8YuTqYpQzHs3d9h0ie/G4g2bOD",
	"IRAEOhQg+e+mcRQS06fLMRAbU+URMbZGefI5dC3vgkgLHMs1fuC/uwiOTW5YwG8KNBxqBdpj6p+2d6O4",
	"pxMQkYfgREBjOycmu32SaNLivZoYIyFgnAGnB9WqdYdpi3q1Yus3XJ7I2p/QNyrB/GiBj/uNzlrplvbX",
	"+pWTuOZ594HTgCwfk1Ac22nA35Xz3SlrXwrravMLuZZhObuXazn9Kq4lrHQdzrVcxRWx/V3LSWaq1eZm",
	"8cNUYI+Yw3pI3BRKky6EKK+NnkZv0oyQQwoUqlw6lOqjzUwCRKGu8ThmH1T28eytbXDP4K+8/9XURROu",
	"6yepJhhck1HKwfWivUE5AeHaKpsv7uTqxkq0oRUZdTPVzdpu04U8bzfMmtU+V/OKnlyvQ6nQxpep3rUY",
	"NQFvVUn64A0sVMhnn52eTrNcWJH5OA2HQpXKjyVBzQ7Yl4rSGytmd8Md668dk8NC2AFiMknpIWbTpokH",
	"tpsLKd3IzjO8662OBt/1fF37d9eNz56H1SjW9Y6ijmlM3Mr+QgqzsfP9lXO6MCrZrT+hV/J0/bmQcii1",
	"B2jSyefwAcbOVO8KS3ODa/XgvV2xJbCG3KoV7j4pXjt1t3yRPExEIlANygdMPib3vhm/jtmRpoRWpOv0",
	"fPVG6AhbeLi937i5h9jpP8JRIZyf3lrlcXqrtIvLtjpMNDzwbtJoNbvukX4hyxw2Yb9yVrTLOOPY9mDG",
	"GYjdoYP3WuUJ5xaPd/cPU9bRwPCLsNdr0xfrD1f622VwKbGsDAnoHNo9OKFBFBaFXKW6uyoSPg7SZmqq",
	"5sOfUFoxwKimzguPo+kGQRr3MF9HUbqkHCQL4I97+EugJ+iKRf7e45tqy1XAgWtks/D9NLu3d9rVl4B5",
	"Z85Cvk3wYqE2HlogT1GaiNm3VJsooMPpTaQJBHT5/CjliWXMN1aepr/S8xVRbbgeG+pOZ5NX6FRHdxPe",
	"frqreR+gf0utqfWh3U0k6h5nE8ZKOxthvvmITenfMGP901FaMXmYwaWGX87i4qsDEUYp/NlZLqzMjEQJ",
	"Em8CnKP3b6cXs7Pj53Gt2GJViCzMmS2KojvVU0aD0vDLsy1zll/wS0qM545bJDY2ejxMZ82PQu8IMAwP",
	"/YpkSKf5I6lgx7UtkvPkRFTq5OaMrTAeGgzzhpOylrmiANSSv63h1mYc7cXBDjmB/dix/v67QXh49m13",
	"YOCaiZ2y68Zq55ttl9x9uPu/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
